version: '3.7'
services:
  mariadb:  
    build: ./db/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql/
    env_file: .env
  nginx:
    build: ./nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    volumes:
      - wp_data:/var/www/
  wordpress:
    build: ./wp/
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/
    env_file: .env

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/db"
  wp_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/wp"
